name: "Integrated Dev Latest"

on:
  push:
    paths:
      - "Dockerfiles/integrated-dev/**"
      - "!Dockerfiles/integrated-dev/latest/README.md"
    branches:
      - "master"
    tags:
      - "integrated-dev-latest-*"

env:
  IMAGE_NAME: "integrated-dev"
  BASE_VERSION: "latest"

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Convert tag to version
        run: echo ::set-env name=IMAGE_TAG::$(echo "${{ github.ref }}" | cut -d"/" -f3 | sed -En "s/^${{ env.IMAGE_NAME }}-(.*)/\1/p")
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ env.IMAGE_TAG }}
          path: Dockerfiles/${{ env.IMAGE_NAME }}/${{ env.BASE_VERSION }}
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
  github-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Convert repository name to lowercase
        run: echo ::set-env name=GITHUB_REPOSITORY::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
      - name: Convert tag to version
        run: echo ::set-env name=IMAGE_TAG::$(echo "${{ github.ref }}" | cut -d"/" -f3 | sed -En "s/^${{ env.IMAGE_NAME }}-(.*)/\1/p")
      - name: Build and Push to Github Package
        uses: docker/build-push-action@v1
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}/${{ env.IMAGE_NAME }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          tags: ${{ env.IMAGE_TAG }}
          path: Dockerfiles/${{ env.IMAGE_NAME }}/${{ env.BASE_VERSION }}
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
