name: "PyTorch 0.5"

on:
  push:
    paths:
      - "Dockerfiles/pytorch/0.5/**"
      - "!Dockerfiles/pytorch/0.5/README.md"
    branches:
      - "master"
    tags:
      - "pytorch-*"
  # workflow_dispatch:
  #   inputs:
  #     ubuntu:
  #       description: "Version of Ubuntu used to build"
  #       required: false
  #       default: "18"
  #     cuda:
  #       description: "Version of CUDA used to build"
  #       required: false
  #       default: "11"

env:
  IMAGE_NAME: "pytorch"
  BASE_VERSION: "0.5"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     ubuntu: [16.04, 18.04]
    #     cuda: [10.1, 10.2, 11.0]
    #     pytorch: [1.6.0, 1.7.0]
    #     python: [3.6, 3.7, 3.8]
    #     include:
    #       - ubuntu: [16.04, 18.04]
    #         cuda: 10.0
    #         pytorch: [1.3.1, 1.4.0]
    #       - ubuntu: 20.04
    #         cuda: 11.0
    #         pytorch: 1.7.0
    #     exclude:
    #       - pytorch: 1.3.1
    #         python: 3.6
    steps:
      # - name: Dump matrix context
      #   env:
      #     MATRIX_CONTEXT: ${{ toJson(matrix) }}
      #   run: echo "$MATRIX_CONTEXT"
      - uses: actions/checkout@v2
      # build-push-action@v2 does not support path for git context yet
      # manually copy context to root
      - name: Copy context for docker build
        run: cp -r Dockerfiles/${{ env.IMAGE_NAME }}/${{ env.BASE_VERSION }}/. .
      - name: Convert repository name to lowercase
        run: echo "GITHUB_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Compose tag for build test
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: echo "IMAGE_TAG=${{ env.BASE_VERSION }}" >> $GITHUB_ENV
      - name: Compose tag for release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo "IMAGE_TAG=$(echo ${{ github.ref }} | cut -d '/' -f 3 | sed -En 's/^${{ env.IMAGE_NAME }}-(.*)/\1/p')" >> $GITHUB_ENV
      - name: Login to DockerHub
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
  # # 2FA enabled is not supported yet, fix this someday
  # update-docker-hub-readme:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Update repository description
  #       uses: peter-evans/dockerhub-description@v2
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #         repository: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
  #         readme-filepath: Dockerfiles/${{ env.IMAGE_NAME }}/${{ env.BASE_VERSION }}/README.md
